#!/usr/bin/env bash
set -euo pipefail

COMMANDER_HOME="${CLAUDE_COMMANDER_HOME:-$HOME/.claude/commander}"
RUNS_DIR="$COMMANDER_HOME/runs"

usage() {
  cat <<'EOF'
Usage: launch-worker.sh --run RUN --task TASK --goal-file FILE [options]

Options:
  --role ROLE                 Default: implementer
  --base REF                  Default: run.json base_ref or HEAD
  --worktree-root DIR         Default: $CLAUDE_COMMANDER_HOME/worktrees/<repo-slug>/<run-id>
  --dry-run                   Print planned operations only

This script creates a verified git worktree and launches codex-unsafe inside it.
EOF
}

realpath_py() { python3 -c 'import os,sys; print(os.path.realpath(sys.argv[1]))' "$1"; }
json_get() { python3 -c 'import json,sys; print(json.load(open(sys.argv[1], encoding="utf-8")).get(sys.argv[2], ""))' "$1" "$2"; }
slug() { printf '%s' "$1" | tr -cs 'A-Za-z0-9._-' '-' | sed 's/^-//;s/-$//' | cut -c1-80; }
prompt_summary() {
  python3 - "$1" <<'PY'
import re, sys
path = sys.argv[1]
text = open(path, encoding='utf-8', errors='replace').read()
patterns = [
    r'(?ims)^##\s*Task goal\s*\n\s*(.+?)(?:\n##\s|\Z)',
    r'(?ims)^##\s*任务目标\s*\n\s*(.+?)(?:\n##\s|\Z)',
    r'(?ims)^##\s*Goal\s*\n\s*(.+?)(?:\n##\s|\Z)',
]
summary = ''
for pat in patterns:
    m = re.search(pat, text)
    if m:
        lines = [ln.strip() for ln in m.group(1).splitlines() if ln.strip() and not ln.strip().startswith('```')]
        summary = ' '.join(lines[:3])
        break
if not summary:
    for line in text.splitlines():
        line = line.strip().lstrip('#').strip()
        if line:
            summary = line
            break
summary = re.sub(r'\s+', ' ', summary).strip()
print(summary[:240] if summary else '(no task summary found)')
PY
}

prepare_codex_home() {
  local target="$1"
  local source="${CODEX_HOME:-$HOME/.codex}"
  mkdir -p "$target"
  chmod 700 "$target"
  python3 - "$source" "$target" <<'PY'
import json, os, shutil, sys
from pathlib import Path
try:
    import tomllib
except ModuleNotFoundError as exc:
    tomllib = None
    tomllib_error = exc
else:
    tomllib_error = None

source = Path(sys.argv[1]).expanduser()
target = Path(sys.argv[2])
target.mkdir(parents=True, exist_ok=True)
os.chmod(target, 0o700)

for name in ("auth.json", "cliproxy.config.toml"):
    src = source / name
    if src.exists() and src.is_file():
        dst = target / name
        shutil.copy2(src, dst)
        os.chmod(dst, 0o600)

cfg_path = source / "config.toml"
out_path = target / "config.toml"
if cfg_path.exists() and tomllib is None:
    print(f"Cannot sanitize Codex config without tomllib: {tomllib_error}", file=sys.stderr)
    raise SystemExit(1)

cfg = {}
if cfg_path.exists():
    cfg = tomllib.loads(cfg_path.read_text(encoding="utf-8"))
keep_top = [
    "model",
    "model_provider",
    "model_reasoning_effort",
    "model_reasoning_summary",
]
selected_provider = cfg.get("model_provider")
model_providers = cfg.get("model_providers", {})
kept = {k: cfg[k] for k in keep_top if k in cfg}
if model_providers:
    if selected_provider and selected_provider in model_providers:
        kept["model_providers"] = {selected_provider: model_providers[selected_provider]}
    else:
        kept["model_providers"] = model_providers

def toml_value(value):
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int) or isinstance(value, float):
        return str(value)
    if isinstance(value, list):
        return "[" + ", ".join(toml_value(v) for v in value) + "]"
    return json.dumps(str(value), ensure_ascii=False)

lines = ["# Generated by claude-commander for an isolated worker CODEX_HOME."]
for key in keep_top:
    if key in kept and not isinstance(kept[key], dict):
        lines.append(f"{key} = {toml_value(kept[key])}")
if "model_providers" in kept:
    for provider, table in kept["model_providers"].items():
        lines.append("")
        lines.append(f"[model_providers.{provider}]")
        for key, value in table.items():
            if isinstance(value, dict):
                continue
            lines.append(f"{key} = {toml_value(value)}")
lines.extend([
    "",
    "[skills]",
    "enabled = false",
])
out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
os.chmod(out_path, 0o600)
PY
}

verify_isolated_codex_home() {
  local worker_home="$1"
  local codex_home="$2"
  local source_codex_home="$3"
  local allowed_root="$4"
  python3 - "$worker_home" "$codex_home" "$source_codex_home" "$allowed_root" <<'PY'
import os, stat, sys
from pathlib import Path

worker_home = Path(sys.argv[1]).resolve()
codex_home = Path(sys.argv[2]).resolve()
source_codex_home = Path(sys.argv[3]).expanduser().resolve()
allowed_root = Path(sys.argv[4]).resolve()
expected_codex_home = worker_home / ".codex"
for path, label in ((worker_home, "worker_home"), (codex_home, "codex_home")):
    try:
        path.relative_to(allowed_root)
    except ValueError:
        print(f"{label} is outside isolated root: {path} not under {allowed_root}", file=sys.stderr)
        raise SystemExit(1)
if codex_home != expected_codex_home:
    print(f"codex_home must be worker_home/.codex: {codex_home} != {expected_codex_home}", file=sys.stderr)
    raise SystemExit(1)
for name in ("superpowers", "skills", "AGENTS.md", "sessions", "logs", "mcp", "plugins"):
    for root in (worker_home, codex_home):
        candidate = root / name
        if candidate.exists():
            print(f"forbidden Codex state copied into isolated home: {candidate}", file=sys.stderr)
            raise SystemExit(1)
config = codex_home / "config.toml"
if config.exists():
    text = config.read_text(encoding="utf-8", errors="replace")
    lowered = text.lower()
    forbidden_text = ["superpowers", str(source_codex_home).lower()]
    for needle in forbidden_text:
        if needle and needle in lowered:
            print(f"generated config.toml contains forbidden reference: {needle}", file=sys.stderr)
            raise SystemExit(1)
for sensitive in (codex_home / "auth.json", codex_home / "cliproxy.config.toml", config):
    if sensitive.exists():
        mode = stat.S_IMODE(sensitive.stat().st_mode)
        if mode & 0o077:
            print(f"sensitive Codex file is group/world accessible: {sensitive} mode={mode:o}", file=sys.stderr)
            raise SystemExit(1)
if codex_home.exists():
    for dirpath, dirnames, filenames in os.walk(codex_home):
        for name in dirnames + filenames:
            path = Path(dirpath) / name
            if not path.is_symlink():
                continue
            target = path.resolve()
            try:
                target.relative_to(source_codex_home)
            except ValueError:
                continue
            print(f"symlink points back to source Codex home: {path} -> {target}", file=sys.stderr)
            raise SystemExit(1)
PY
}

RUN=""; TASK=""; ROLE="implementer"; GOAL_FILE=""; BASE=""; WORKTREE_ROOT=""; DRY_RUN=false
while [[ $# -gt 0 ]]; do
  case "$1" in
    --run) RUN="${2:?}"; shift 2 ;;
    --task) TASK="${2:?}"; shift 2 ;;
    --role) ROLE="${2:?}"; shift 2 ;;
    --goal-file) GOAL_FILE="${2:?}"; shift 2 ;;
    --base) BASE="${2:?}"; shift 2 ;;
    --worktree-root) WORKTREE_ROOT="${2:?}"; shift 2 ;;
    --dry-run) DRY_RUN=true; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown option: $1" >&2; usage; exit 2 ;;
  esac
done

[[ -n "$RUN" ]] || { echo "missing --run" >&2; exit 2; }
[[ -n "$TASK" ]] || { echo "missing --task" >&2; exit 2; }
[[ -n "$GOAL_FILE" ]] || { echo "missing --goal-file" >&2; exit 2; }
[[ -f "$GOAL_FILE" ]] || { echo "goal file not found: $GOAL_FILE" >&2; exit 1; }
command -v git >/dev/null || { echo "git missing" >&2; exit 1; }
command -v codex-unsafe >/dev/null || { echo "codex-unsafe missing" >&2; exit 1; }

if [[ -d "$RUN" ]]; then
  RUN_DIR="$(realpath_py "$RUN")"
  RUN_ID="$(basename "$RUN_DIR")"
else
  RUN_ID="$RUN"
  RUN_DIR="$RUNS_DIR/$RUN_ID"
fi
[[ -d "$RUN_DIR" ]] || { echo "run directory not found: $RUN_DIR" >&2; exit 1; }
RUN_JSON="$RUN_DIR/run.json"
[[ -f "$RUN_JSON" ]] || { echo "run.json not found: $RUN_JSON" >&2; exit 1; }

REPO_ROOT="$(json_get "$RUN_JSON" repo_root)"
[[ -n "$REPO_ROOT" && -d "$REPO_ROOT" ]] || { echo "repo root from run.json not found: $REPO_ROOT" >&2; exit 1; }
REPO_TOP="$(git -C "$REPO_ROOT" rev-parse --show-toplevel)"
BASE="${BASE:-$(json_get "$RUN_JSON" base_ref)}"
BASE="${BASE:-HEAD}"
REPO_SLUG="$(json_get "$RUN_JSON" repo_slug)"
REPO_SLUG="${REPO_SLUG:-$(slug "$(basename "$REPO_TOP")")}"

TASK_SAFE="$(slug "$TASK")"
[[ -n "$TASK_SAFE" ]] || { echo "invalid task id: $TASK" >&2; exit 2; }
BRANCH="commander/$RUN_ID/$TASK_SAFE"
if [[ -z "$WORKTREE_ROOT" ]]; then
  WORKTREE_ROOT="$COMMANDER_HOME/worktrees/$REPO_SLUG/$RUN_ID"
fi
CANON_ROOT="$(realpath_py "$WORKTREE_ROOT")"
PROJECT_ALLOWED_ROOT="$(realpath_py "$REPO_TOP/.claude/commander/worktrees")"
GLOBAL_ALLOWED_ROOT="$(realpath_py "$COMMANDER_HOME/worktrees")"
case "$CANON_ROOT" in
  "$PROJECT_ALLOWED_ROOT"|"$PROJECT_ALLOWED_ROOT"/*|"$GLOBAL_ALLOWED_ROOT"|"$GLOBAL_ALLOWED_ROOT"/*) ;;
  *)
    if [[ "${CLAUDE_COMMANDER_ALLOW_CUSTOM_WORKTREE_ROOT:-0}" != "1" ]]; then
      echo "refusing custom worktree root outside allowed Commander roots: $CANON_ROOT" >&2
      echo "allowed: $PROJECT_ALLOWED_ROOT or $GLOBAL_ALLOWED_ROOT" >&2
      exit 1
    fi
    ;;
esac
WORKTREE_PATH="$CANON_ROOT/$TASK_SAFE"
PROMPT_COPY="$RUN_DIR/prompts/$TASK_SAFE.md"
LOG_PATH="$RUN_DIR/logs/$TASK_SAFE.jsonl"
LAST_MESSAGE="$RUN_DIR/logs/$TASK_SAFE.last.md"
WORKER_JSON="$RUN_DIR/workers/$TASK_SAFE.json"
EXIT_JSON="$RUN_DIR/workers/$TASK_SAFE.exit.json"
TASK_STATE_JSON="$RUN_DIR/status/$TASK_SAFE.json"
WORKER_HOME="$RUN_DIR/codex-home/$TASK_SAFE/home"
WORKER_CODEX_HOME="$WORKER_HOME/.codex"
WORKER_XDG_CONFIG_HOME="$WORKER_HOME/.config"
WORKER_XDG_CACHE_HOME="$WORKER_HOME/.cache"
WORKER_XDG_DATA_HOME="$WORKER_HOME/.local/share"
SOURCE_CODEX_HOME="${CODEX_HOME:-$HOME/.codex}"
CODEX_BIN="$(command -v codex-unsafe)"
TASK_SUMMARY="$(prompt_summary "$GOAL_FILE")"

case "$WORKTREE_PATH" in
  "$CANON_ROOT"/*) ;;
  *) echo "refusing worktree outside root: $WORKTREE_PATH" >&2; exit 1 ;;
esac
[[ "$(realpath_py "$WORKTREE_PATH")" != "$CANON_ROOT" ]] || { echo "refusing worktree at root: $WORKTREE_PATH" >&2; exit 1; }
[[ ! -e "$WORKTREE_PATH" ]] || { echo "worktree already exists: $WORKTREE_PATH" >&2; exit 1; }

cat <<EOF
# Launch plan
run: $RUN_ID
task: $TASK_SAFE
role: $ROLE
task_summary: $TASK_SUMMARY
repo: $REPO_TOP
base: $BASE
branch: $BRANCH
worktree_root: $CANON_ROOT
worktree: $WORKTREE_PATH
prompt: $PROMPT_COPY
log: $LOG_PATH
exit: $EXIT_JSON
worker_home: $WORKER_HOME
codex_home: $WORKER_CODEX_HOME
xdg_config_home: $WORKER_XDG_CONFIG_HOME
xdg_cache_home: $WORKER_XDG_CACHE_HOME
xdg_data_home: $WORKER_XDG_DATA_HOME
codex: $CODEX_BIN
EOF

if [[ "$DRY_RUN" == true ]]; then
  echo "dry_run: true; no worktree created and no worker launched"
  exit 0
fi

mkdir -p "$WORKTREE_ROOT" "$RUN_DIR/prompts" "$RUN_DIR/logs" "$RUN_DIR/workers" "$RUN_DIR/reports" "$RUN_DIR/status" "$RUN_DIR/codex-home" "$WORKER_HOME" "$WORKER_XDG_CONFIG_HOME" "$WORKER_XDG_CACHE_HOME" "$WORKER_XDG_DATA_HOME"
chmod 700 "$WORKER_HOME" "$WORKER_XDG_CONFIG_HOME" "$WORKER_XDG_CACHE_HOME" "$WORKER_HOME/.local" "$WORKER_XDG_DATA_HOME"
prepare_codex_home "$WORKER_CODEX_HOME"
verify_isolated_codex_home "$WORKER_HOME" "$WORKER_CODEX_HOME" "$SOURCE_CODEX_HOME" "$RUN_DIR/codex-home/$TASK_SAFE"
GOAL_REAL="$(realpath_py "$GOAL_FILE")"
PROMPT_REAL_TARGET="$(python3 -c 'import os,sys; print(os.path.realpath(os.path.dirname(sys.argv[1])) + "/" + os.path.basename(sys.argv[1]))' "$PROMPT_COPY")"
if [[ "$GOAL_REAL" != "$PROMPT_REAL_TARGET" ]]; then
  cp "$GOAL_FILE" "$PROMPT_COPY"
fi

git -C "$REPO_TOP" rev-parse --verify "$BASE" >/dev/null
if git -C "$REPO_TOP" show-ref --verify --quiet "refs/heads/$BRANCH"; then
  echo "branch already exists: $BRANCH" >&2
  exit 1
fi

git -C "$REPO_TOP" worktree add -b "$BRANCH" "$WORKTREE_PATH" "$BASE"
TOP="$(git -C "$WORKTREE_PATH" rev-parse --show-toplevel)"
TOP_REAL="$(realpath_py "$TOP")"
WT_REAL="$(realpath_py "$WORKTREE_PATH")"
[[ "$TOP_REAL" == "$WT_REAL" ]] || { echo "git top-level mismatch: $TOP_REAL != $WT_REAL" >&2; exit 1; }
CURRENT_BRANCH="$(git -C "$WORKTREE_PATH" branch --show-current)"
[[ "$CURRENT_BRANCH" == "$BRANCH" ]] || { echo "branch mismatch: $CURRENT_BRANCH != $BRANCH" >&2; exit 1; }

# Feed prompt through stdin. Do not pass '-' or a prompt positional; codex exec reads stdin when no prompt is provided.
# Detach the worker into its OWN process group so it survives teardown of the
# launching shell / harness process group. macOS has no setsid, so use job
# control (set -m => the job gets its own pgid) + nohup (ignore SIGHUP) + disown.
set -m
nohup bash -c '
  wt="$1"; prompt="$2"; log="$3"; last="$4"; exit_json="$5"; state_json="$6"; run_id="$7"; task_id="$8"; codex_home="$9"; worker_home="${10}"; xdg_config_home="${11}"; xdg_cache_home="${12}"; xdg_data_home="${13}"
  HOME="$worker_home" CODEX_HOME="$codex_home" XDG_CONFIG_HOME="$xdg_config_home" XDG_CACHE_HOME="$xdg_cache_home" XDG_DATA_HOME="$xdg_data_home" codex-unsafe exec --ignore-rules --cd "$wt" --json --color never --output-last-message "$last" < "$prompt" >> "$log" 2>&1
  rc=$?
  python3 - "$exit_json" "$state_json" "$run_id" "$task_id" "$rc" "$log" "$last" <<'"'"'PY'"'"'
import json, sys, datetime
path, state_path, run_id, task_id, rc, log, last = sys.argv[1:]
rc_i = int(rc)
now = datetime.datetime.now(datetime.UTC).replace(microsecond=0).isoformat().replace("+00:00", "Z")
status = "succeeded" if rc_i == 0 else "failed"
data = {
  "run_id": run_id,
  "task_id": task_id,
  "status": status,
  "exit_code": rc_i,
  "finished_at": now,
  "log_path": log,
  "last_message_path": last,
}
with open(path, "w", encoding="utf-8") as f:
  json.dump(data, f, ensure_ascii=False, indent=2)
  f.write("\n")
try:
  state = json.load(open(state_path, encoding="utf-8"))
except Exception:
  state = {"task_id": task_id, "history": []}
state["task_id"] = task_id
state["status"] = "succeeded_unreviewed" if rc_i == 0 else "blocked_failed_check"
state["updated_at"] = now
state["note"] = f"worker exited with code {rc_i}"
state.setdefault("history", []).append({"status": state["status"], "note": state["note"], "at": now})
with open(state_path, "w", encoding="utf-8") as f:
  json.dump(state, f, ensure_ascii=False, indent=2)
  f.write("\n")
PY
  exit "$rc"
' _ "$WORKTREE_PATH" "$PROMPT_COPY" "$LOG_PATH" "$LAST_MESSAGE" "$EXIT_JSON" "$TASK_STATE_JSON" "$RUN_ID" "$TASK_SAFE" "$WORKER_CODEX_HOME" "$WORKER_HOME" "$WORKER_XDG_CONFIG_HOME" "$WORKER_XDG_CACHE_HOME" "$WORKER_XDG_DATA_HOME" &
PID=$!
set +m
disown "$PID" 2>/dev/null || true

python3 - "$WORKER_JSON" "$RUN_ID" "$TASK_SAFE" "$ROLE" "$TASK_SUMMARY" "$WORKTREE_PATH" "$BRANCH" "$BASE" "$PID" "$LOG_PATH" "$LAST_MESSAGE" "$PROMPT_COPY" "$CODEX_BIN" "$EXIT_JSON" "$WORKER_CODEX_HOME" "$WORKER_HOME" "$WORKER_XDG_CONFIG_HOME" "$WORKER_XDG_CACHE_HOME" "$WORKER_XDG_DATA_HOME" <<'PY'
import json, sys, datetime
(path, run_id, task_id, role, task_summary, wt, branch, base, pid, log, last, prompt, binpath, exit_path, codex_home, worker_home, xdg_config_home, xdg_cache_home, xdg_data_home) = sys.argv[1:]
data = {
  "run_id": run_id,
  "task_id": task_id,
  "role": role,
  "task_summary": task_summary,
  "worktree_path": wt,
  "branch": branch,
  "base_ref": base,
  "pid": int(pid),
  "status": "running",
  "log_path": log,
  "last_message_path": last,
  "exit_path": exit_path,
  "prompt_path": prompt,
  "codex_bin": binpath,
  "worker_home": worker_home,
  "codex_home": codex_home,
  "xdg_config_home": xdg_config_home,
  "xdg_cache_home": xdg_cache_home,
  "xdg_data_home": xdg_data_home,
  "codex_home_verified": True,
  "argv": ["env", "HOME=" + worker_home, "CODEX_HOME=" + codex_home, "XDG_CONFIG_HOME=" + xdg_config_home, "XDG_CACHE_HOME=" + xdg_cache_home, "XDG_DATA_HOME=" + xdg_data_home, "codex-unsafe", "exec", "--ignore-rules", "--cd", wt, "--json", "--color", "never", "--output-last-message", last],
  "attempt": 1,
  "started_at": datetime.datetime.now(datetime.UTC).replace(microsecond=0).isoformat().replace('+00:00','Z'),
  "review_status": "not_reviewed"
}
with open(path, "w", encoding="utf-8") as f:
  json.dump(data, f, ensure_ascii=False, indent=2)
  f.write("\n")
PY

python3 - "$TASK_STATE_JSON" "$RUN_ID" "$TASK_SAFE" "$PID" <<'PY'
import json, sys, datetime
path, run_id, task_id, pid = sys.argv[1:]
now = datetime.datetime.now(datetime.UTC).replace(microsecond=0).isoformat().replace('+00:00','Z')
data = {
  "run_id": run_id,
  "task_id": task_id,
  "status": "running",
  "pid": int(pid),
  "updated_at": now,
  "note": "worker launched",
  "history": [{"status": "running", "note": "worker launched", "at": now}],
}
with open(path, "w", encoding="utf-8") as f:
  json.dump(data, f, ensure_ascii=False, indent=2)
  f.write("\n")
PY

echo "worker_pid: $PID"
echo "worker_state: $WORKER_JSON"
echo "task_state: $TASK_STATE_JSON"
