#!/usr/bin/env bash
set -euo pipefail

COMMANDER_HOME="${CLAUDE_COMMANDER_HOME:-$HOME/.claude/commander}"
RUNS_DIR="$COMMANDER_HOME/runs"

usage() {
  cat <<'EOF'
Usage: review-worker.sh --run RUN --task TASK [--run-codex]

Collects non-mutating diff/status artifacts and writes a reviewer prompt. By default it does not launch Codex review.
EOF
}

realpath_py() { python3 -c 'import os,sys; print(os.path.realpath(sys.argv[1]))' "$1"; }
json_get() { python3 -c 'import json,sys; print(json.load(open(sys.argv[1], encoding="utf-8")).get(sys.argv[2], ""))' "$1" "$2"; }
slug() { printf '%s' "$1" | tr -cs 'A-Za-z0-9._-' '-' | sed 's/^-//;s/-$//' | cut -c1-80; }
sha256_file() { python3 -c 'import hashlib,sys; print(hashlib.sha256(open(sys.argv[1], "rb").read()).hexdigest())' "$1"; }

prepare_codex_home() {
  local target="$1"
  local source="${CODEX_HOME:-$HOME/.codex}"
  mkdir -p "$target"
  chmod 700 "$target"
  python3 - "$source" "$target" <<'PY'
import json, os, shutil, sys
from pathlib import Path
try:
    import tomllib
except ModuleNotFoundError as exc:
    tomllib = None
    tomllib_error = exc
else:
    tomllib_error = None

source = Path(sys.argv[1]).expanduser()
target = Path(sys.argv[2])
target.mkdir(parents=True, exist_ok=True)
os.chmod(target, 0o700)

for name in ("auth.json", "cliproxy.config.toml"):
    src = source / name
    if src.exists() and src.is_file():
        dst = target / name
        shutil.copy2(src, dst)
        os.chmod(dst, 0o600)

cfg_path = source / "config.toml"
out_path = target / "config.toml"
if cfg_path.exists() and tomllib is None:
    print(f"Cannot sanitize Codex config without tomllib: {tomllib_error}", file=sys.stderr)
    raise SystemExit(1)

cfg = {}
if cfg_path.exists():
    cfg = tomllib.loads(cfg_path.read_text(encoding="utf-8"))
keep_top = [
    "model",
    "model_provider",
    "model_reasoning_effort",
    "model_reasoning_summary",
]
selected_provider = cfg.get("model_provider")
model_providers = cfg.get("model_providers", {})
kept = {k: cfg[k] for k in keep_top if k in cfg}
if model_providers:
    if selected_provider and selected_provider in model_providers:
        kept["model_providers"] = {selected_provider: model_providers[selected_provider]}
    else:
        kept["model_providers"] = model_providers

def toml_value(value):
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int) or isinstance(value, float):
        return str(value)
    if isinstance(value, list):
        return "[" + ", ".join(toml_value(v) for v in value) + "]"
    return json.dumps(str(value), ensure_ascii=False)

lines = ["# Generated by claude-commander for an isolated worker CODEX_HOME."]
for key in keep_top:
    if key in kept and not isinstance(kept[key], dict):
        lines.append(f"{key} = {toml_value(kept[key])}")
if "model_providers" in kept:
    for provider, table in kept["model_providers"].items():
        lines.append("")
        lines.append(f"[model_providers.{provider}]")
        for key, value in table.items():
            if isinstance(value, dict):
                continue
            lines.append(f"{key} = {toml_value(value)}")
lines.extend([
    "",
    "[skills]",
    "enabled = false",
])
out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
os.chmod(out_path, 0o600)
PY
}

verify_isolated_codex_home() {
  local worker_home="$1"
  local codex_home="$2"
  local source_codex_home="$3"
  local allowed_root="$4"
  python3 - "$worker_home" "$codex_home" "$source_codex_home" "$allowed_root" <<'PY'
import os, stat, sys
from pathlib import Path

worker_home = Path(sys.argv[1]).resolve()
codex_home = Path(sys.argv[2]).resolve()
source_codex_home = Path(sys.argv[3]).expanduser().resolve()
allowed_root = Path(sys.argv[4]).resolve()
expected_codex_home = worker_home / ".codex"
for path, label in ((worker_home, "worker_home"), (codex_home, "codex_home")):
    try:
        path.relative_to(allowed_root)
    except ValueError:
        print(f"{label} is outside isolated root: {path} not under {allowed_root}", file=sys.stderr)
        raise SystemExit(1)
if codex_home != expected_codex_home:
    print(f"codex_home must be worker_home/.codex: {codex_home} != {expected_codex_home}", file=sys.stderr)
    raise SystemExit(1)
for name in ("superpowers", "skills", "AGENTS.md", "sessions", "logs", "mcp", "plugins"):
    for root in (worker_home, codex_home):
        candidate = root / name
        if candidate.exists():
            print(f"forbidden Codex state copied into isolated home: {candidate}", file=sys.stderr)
            raise SystemExit(1)
config = codex_home / "config.toml"
if config.exists():
    text = config.read_text(encoding="utf-8", errors="replace")
    lowered = text.lower()
    forbidden_text = ["superpowers", str(source_codex_home).lower()]
    for needle in forbidden_text:
        if needle and needle in lowered:
            print(f"generated config.toml contains forbidden reference: {needle}", file=sys.stderr)
            raise SystemExit(1)
for sensitive in (codex_home / "auth.json", codex_home / "cliproxy.config.toml", config):
    if sensitive.exists():
        mode = stat.S_IMODE(sensitive.stat().st_mode)
        if mode & 0o077:
            print(f"sensitive Codex file is group/world accessible: {sensitive} mode={mode:o}", file=sys.stderr)
            raise SystemExit(1)
if codex_home.exists():
    for dirpath, dirnames, filenames in os.walk(codex_home):
        for name in dirnames + filenames:
            path = Path(dirpath) / name
            if not path.is_symlink():
                continue
            target = path.resolve()
            try:
                target.relative_to(source_codex_home)
            except ValueError:
                continue
            print(f"symlink points back to source Codex home: {path} -> {target}", file=sys.stderr)
            raise SystemExit(1)
PY
}

RUN=""; TASK=""; RUN_CODEX=false
while [[ $# -gt 0 ]]; do
  case "$1" in
    --run) RUN="${2:?}"; shift 2 ;;
    --task) TASK="${2:?}"; shift 2 ;;
    --run-codex) RUN_CODEX=true; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown option: $1" >&2; usage; exit 2 ;;
  esac
done
[[ -n "$RUN" && -n "$TASK" ]] || { usage; exit 2; }
if [[ -d "$RUN" ]]; then RUN_DIR="$(realpath_py "$RUN")"; RUN_ID="$(basename "$RUN_DIR")"; else RUN_ID="$RUN"; RUN_DIR="$RUNS_DIR/$RUN"; fi
TASK_SAFE="$(slug "$TASK")"
WORKER_JSON="$RUN_DIR/workers/$TASK_SAFE.json"
[[ -f "$WORKER_JSON" ]] || { echo "worker not found: $WORKER_JSON" >&2; exit 1; }

WT="$(json_get "$WORKER_JSON" worktree_path)"
BASE="$(json_get "$WORKER_JSON" base_ref)"
BRANCH="$(json_get "$WORKER_JSON" branch)"
LOG="$(json_get "$WORKER_JSON" log_path)"
[[ -d "$WT" ]] || { echo "worktree missing: $WT" >&2; exit 1; }
mkdir -p "$RUN_DIR/diffs" "$RUN_DIR/reviews"
DIFF_FILE="$RUN_DIR/diffs/$TASK_SAFE.diff"
STAT_FILE="$RUN_DIR/diffs/$TASK_SAFE.stat.txt"
STATUS_FILE="$RUN_DIR/diffs/$TASK_SAFE.status.txt"
ALT_INDEX="$RUN_DIR/diffs/$TASK_SAFE.review.index"
SNAPSHOT_JSON="$RUN_DIR/reviews/$TASK_SAFE.snapshot.json"
REVIEW_PROMPT="$RUN_DIR/reviews/$TASK_SAFE.prompt.md"
REVIEW_OUT="$RUN_DIR/reviews/$TASK_SAFE.codex-review.md"

# Capture status and a full diff without mutating the worker's real index.
# The alternate index is populated from HEAD and then filled with the current
# worktree contents, including untracked files, so review sees exactly what a
# later `git add -A && commit` would include.
git -C "$WT" status --short > "$STATUS_FILE"
rm -f "$ALT_INDEX"
GIT_INDEX_FILE="$ALT_INDEX" git -C "$WT" read-tree HEAD
GIT_INDEX_FILE="$ALT_INDEX" git -C "$WT" add -A
git -C "$WT" diff --stat "$BASE" -- > "$STAT_FILE" || true
GIT_INDEX_FILE="$ALT_INDEX" git -C "$WT" diff --cached --stat "$BASE" -- > "$STAT_FILE" || true
GIT_INDEX_FILE="$ALT_INDEX" git -C "$WT" diff --cached "$BASE" -- > "$DIFF_FILE" || true
WORKER_HEAD="$(git -C "$WT" rev-parse HEAD)"
STATUS_SHA="$(sha256_file "$STATUS_FILE")"
DIFF_SHA="$(sha256_file "$DIFF_FILE")"

python3 - "$SNAPSHOT_JSON" "$RUN_ID" "$TASK_SAFE" "$BASE" "$BRANCH" "$WORKER_HEAD" "$STATUS_SHA" "$DIFF_SHA" "$STATUS_FILE" "$STAT_FILE" "$DIFF_FILE" <<'PY'
import json, sys, datetime
(path, run_id, task_id, base, branch, head, status_sha, diff_sha, status_file, stat_file, diff_file) = sys.argv[1:]
data = {
  "run_id": run_id,
  "task_id": task_id,
  "base_ref": base,
  "worker_branch": branch,
  "worker_head": head,
  "status_sha256": status_sha,
  "diff_sha256": diff_sha,
  "created_at": datetime.datetime.now(datetime.UTC).replace(microsecond=0).isoformat().replace('+00:00','Z'),
  "status_file": status_file,
  "stat_file": stat_file,
  "diff_file": diff_file,
}
with open(path, "w", encoding="utf-8") as f:
  json.dump(data, f, ensure_ascii=False, indent=2)
  f.write("\n")
PY

cat > "$REVIEW_PROMPT" <<EOF
# Review worker $TASK_SAFE

You are a read-only reviewer. Do not modify files.

Worktree: $WT
Base ref: $BASE
Worker branch: $BRANCH
Worker HEAD: $WORKER_HEAD
Worker log: $LOG
Status file: $STATUS_FILE
Diff stat file: $STAT_FILE
Diff file: $DIFF_FILE
Snapshot metadata: $SNAPSHOT_JSON
Reviewed diff sha256: $DIFF_SHA

Review for:
1. Correctness bugs
2. Scope drift or unrelated changes
3. Missing or broken tests/checks
4. Safety boundary violations
5. Simplicity and maintainability
6. Merge readiness

Return YAML:
decision: PASS | PASS_WITH_NOTES | FAIL_REVISE | FAIL_ABORT
reviewed_diff_sha256: "$DIFF_SHA"
reviewed_worker_head: "$WORKER_HEAD"
verification_status: PASS | NOT_APPLICABLE | FAIL | MISSING
verification_evidence:
  - command: "<command or NOT_APPLICABLE>"
    exit_code: 0
    summary: "<observed result or why verification is not applicable>"
summary: "..."
blocking_findings: []
nonblocking_findings: []
verification_notes: []
merge_recommendation: merge | revise | abort
EOF

cat <<EOF
review_prompt: $REVIEW_PROMPT
snapshot_file: $SNAPSHOT_JSON
diff_sha256: $DIFF_SHA
diff_file: $DIFF_FILE
status_file: $STATUS_FILE
stat_file: $STAT_FILE
EOF

if [[ "$RUN_CODEX" == true ]]; then
  command -v codex >/dev/null || { echo "codex missing" >&2; exit 1; }
  REVIEW_HOME="$RUN_DIR/codex-home/$TASK_SAFE-review/home"
  REVIEW_CODEX_HOME="$REVIEW_HOME/.codex"
  REVIEW_XDG_CONFIG_HOME="$REVIEW_HOME/.config"
  REVIEW_XDG_CACHE_HOME="$REVIEW_HOME/.cache"
  REVIEW_XDG_DATA_HOME="$REVIEW_HOME/.local/share"
  SOURCE_CODEX_HOME="${CODEX_HOME:-$HOME/.codex}"
  mkdir -p "$REVIEW_HOME" "$REVIEW_XDG_CONFIG_HOME" "$REVIEW_XDG_CACHE_HOME" "$REVIEW_XDG_DATA_HOME"
  chmod 700 "$REVIEW_HOME" "$REVIEW_XDG_CONFIG_HOME" "$REVIEW_XDG_CACHE_HOME" "$REVIEW_HOME/.local" "$REVIEW_XDG_DATA_HOME"
  prepare_codex_home "$REVIEW_CODEX_HOME"
  verify_isolated_codex_home "$REVIEW_HOME" "$REVIEW_CODEX_HOME" "$SOURCE_CODEX_HOME" "$RUN_DIR/codex-home/$TASK_SAFE-review"
  (
    cd "$WT"
    HOME="$REVIEW_HOME" CODEX_HOME="$REVIEW_CODEX_HOME" XDG_CONFIG_HOME="$REVIEW_XDG_CONFIG_HOME" XDG_CACHE_HOME="$REVIEW_XDG_CACHE_HOME" XDG_DATA_HOME="$REVIEW_XDG_DATA_HOME" codex review --base "$BASE" > "$REVIEW_OUT" 2>&1
  )
  echo "codex_review_output: $REVIEW_OUT"
fi
